"""Initial migration

Revision ID: 5715d90eb7c1
Revises: 
Create Date: 2025-12-01 21:08:29.506644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5715d90eb7c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('bottles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('abv', sa.Float(), nullable=True),
    sa.Column('price_paid', sa.Float(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('tasted', sa.Boolean(), nullable=True),
    sa.Column('tasting_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('tasting_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bottles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bottles_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_bottles_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_bottles_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bottles_tasted'), ['tasted'], unique=False)
        batch_op.create_index(batch_op.f('ix_bottles_user_id'), ['user_id'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('weeks', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_user_id'), ['user_id'], unique=False)

    op.create_table('user_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tasting_frequency', sa.String(length=20), nullable=True),
    sa.Column('custom_interval_days', sa.Integer(), nullable=True),
    sa.Column('preferred_days', sa.String(length=100), nullable=True),
    sa.Column('avoid_dates', sa.Text(), nullable=True),
    sa.Column('category_preferences', sa.Text(), nullable=True),
    sa.Column('seasonal_adjustments', sa.Boolean(), nullable=True),
    sa.Column('min_days_between_category', sa.Integer(), nullable=True),
    sa.Column('default_schedule_weeks', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('schedule_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('bottle_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_repeat', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bottle_id'], ['bottles.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_items_bottle_id'), ['bottle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_items_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_items_schedule_id'), ['schedule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_items_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_schedule_items_date'))
        batch_op.drop_index(batch_op.f('ix_schedule_items_bottle_id'))

    op.drop_table('schedule_items')
    op.drop_table('user_configs')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_user_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('bottles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bottles_user_id'))
        batch_op.drop_index(batch_op.f('ix_bottles_tasted'))
        batch_op.drop_index(batch_op.f('ix_bottles_name'))
        batch_op.drop_index(batch_op.f('ix_bottles_category'))
        batch_op.drop_index(batch_op.f('ix_bottles_barcode'))

    op.drop_table('bottles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
